[variables]
NIXPACKS_PHP_ROOT_DIR = "public"
NODE_ENV = "production"

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build",
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear"
]
